services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src/tg.post-site
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    command: server --ignoreCache --disableFastRender --bind=0.0.0.0 --watch --poll 500ms -s .




