spring:
  config:
    import:
      - .env[.properties]

server:
  port: 8081

telegram:
  client:
    api-id: ${TELEGRAM_API_ID}
    api-hash: ${TELEGRAM_API_HASH}
    session-dir: ${TELEGRAM_SESSION_DIR}
    data-dir: ${TELEGRAM_DATA_DIR}
    download-dir: ${TELEGRAM_DOWNLOAD_DIR}
  bot:
    username: ${TELEGRAM_BOT_USERNAME}

hugo:
  path-to-content-directory: ${HUGO_PATH_TO_CONTENT_DIRECTORY}